// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/chatpuppy/puppychat/internal/ent/group"
	"github.com/chatpuppy/puppychat/internal/ent/groupmember"
	"github.com/chatpuppy/puppychat/internal/ent/member"
	"github.com/chatpuppy/puppychat/internal/ent/predicate"
)

// GroupMemberQuery is the builder for querying GroupMember entities.
type GroupMemberQuery struct {
	config
	limit       *int
	offset      *int
	unique      *bool
	order       []OrderFunc
	fields      []string
	predicates  []predicate.GroupMember
	withMember  *MemberQuery
	withGroup   *GroupQuery
	withInviter *MemberQuery
	modifiers   []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the GroupMemberQuery builder.
func (gmq *GroupMemberQuery) Where(ps ...predicate.GroupMember) *GroupMemberQuery {
	gmq.predicates = append(gmq.predicates, ps...)
	return gmq
}

// Limit adds a limit step to the query.
func (gmq *GroupMemberQuery) Limit(limit int) *GroupMemberQuery {
	gmq.limit = &limit
	return gmq
}

// Offset adds an offset step to the query.
func (gmq *GroupMemberQuery) Offset(offset int) *GroupMemberQuery {
	gmq.offset = &offset
	return gmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (gmq *GroupMemberQuery) Unique(unique bool) *GroupMemberQuery {
	gmq.unique = &unique
	return gmq
}

// Order adds an order step to the query.
func (gmq *GroupMemberQuery) Order(o ...OrderFunc) *GroupMemberQuery {
	gmq.order = append(gmq.order, o...)
	return gmq
}

// QueryMember chains the current query on the "member" edge.
func (gmq *GroupMemberQuery) QueryMember() *MemberQuery {
	query := &MemberQuery{config: gmq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := gmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := gmq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(groupmember.Table, groupmember.FieldID, selector),
			sqlgraph.To(member.Table, member.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, groupmember.MemberTable, groupmember.MemberColumn),
		)
		fromU = sqlgraph.SetNeighbors(gmq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGroup chains the current query on the "group" edge.
func (gmq *GroupMemberQuery) QueryGroup() *GroupQuery {
	query := &GroupQuery{config: gmq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := gmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := gmq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(groupmember.Table, groupmember.FieldID, selector),
			sqlgraph.To(group.Table, group.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, groupmember.GroupTable, groupmember.GroupColumn),
		)
		fromU = sqlgraph.SetNeighbors(gmq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryInviter chains the current query on the "inviter" edge.
func (gmq *GroupMemberQuery) QueryInviter() *MemberQuery {
	query := &MemberQuery{config: gmq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := gmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := gmq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(groupmember.Table, groupmember.FieldID, selector),
			sqlgraph.To(member.Table, member.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, groupmember.InviterTable, groupmember.InviterColumn),
		)
		fromU = sqlgraph.SetNeighbors(gmq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first GroupMember entity from the query.
// Returns a *NotFoundError when no GroupMember was found.
func (gmq *GroupMemberQuery) First(ctx context.Context) (*GroupMember, error) {
	nodes, err := gmq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{groupmember.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (gmq *GroupMemberQuery) FirstX(ctx context.Context) *GroupMember {
	node, err := gmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first GroupMember ID from the query.
// Returns a *NotFoundError when no GroupMember ID was found.
func (gmq *GroupMemberQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = gmq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{groupmember.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (gmq *GroupMemberQuery) FirstIDX(ctx context.Context) string {
	id, err := gmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single GroupMember entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one GroupMember entity is found.
// Returns a *NotFoundError when no GroupMember entities are found.
func (gmq *GroupMemberQuery) Only(ctx context.Context) (*GroupMember, error) {
	nodes, err := gmq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{groupmember.Label}
	default:
		return nil, &NotSingularError{groupmember.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (gmq *GroupMemberQuery) OnlyX(ctx context.Context) *GroupMember {
	node, err := gmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only GroupMember ID in the query.
// Returns a *NotSingularError when more than one GroupMember ID is found.
// Returns a *NotFoundError when no entities are found.
func (gmq *GroupMemberQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = gmq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{groupmember.Label}
	default:
		err = &NotSingularError{groupmember.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (gmq *GroupMemberQuery) OnlyIDX(ctx context.Context) string {
	id, err := gmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of GroupMembers.
func (gmq *GroupMemberQuery) All(ctx context.Context) ([]*GroupMember, error) {
	if err := gmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return gmq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (gmq *GroupMemberQuery) AllX(ctx context.Context) []*GroupMember {
	nodes, err := gmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of GroupMember IDs.
func (gmq *GroupMemberQuery) IDs(ctx context.Context) ([]string, error) {
	var ids []string
	if err := gmq.Select(groupmember.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (gmq *GroupMemberQuery) IDsX(ctx context.Context) []string {
	ids, err := gmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (gmq *GroupMemberQuery) Count(ctx context.Context) (int, error) {
	if err := gmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return gmq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (gmq *GroupMemberQuery) CountX(ctx context.Context) int {
	count, err := gmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (gmq *GroupMemberQuery) Exist(ctx context.Context) (bool, error) {
	if err := gmq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return gmq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (gmq *GroupMemberQuery) ExistX(ctx context.Context) bool {
	exist, err := gmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the GroupMemberQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (gmq *GroupMemberQuery) Clone() *GroupMemberQuery {
	if gmq == nil {
		return nil
	}
	return &GroupMemberQuery{
		config:      gmq.config,
		limit:       gmq.limit,
		offset:      gmq.offset,
		order:       append([]OrderFunc{}, gmq.order...),
		predicates:  append([]predicate.GroupMember{}, gmq.predicates...),
		withMember:  gmq.withMember.Clone(),
		withGroup:   gmq.withGroup.Clone(),
		withInviter: gmq.withInviter.Clone(),
		// clone intermediate query.
		sql:    gmq.sql.Clone(),
		path:   gmq.path,
		unique: gmq.unique,
	}
}

// WithMember tells the query-builder to eager-load the nodes that are connected to
// the "member" edge. The optional arguments are used to configure the query builder of the edge.
func (gmq *GroupMemberQuery) WithMember(opts ...func(*MemberQuery)) *GroupMemberQuery {
	query := &MemberQuery{config: gmq.config}
	for _, opt := range opts {
		opt(query)
	}
	gmq.withMember = query
	return gmq
}

// WithGroup tells the query-builder to eager-load the nodes that are connected to
// the "group" edge. The optional arguments are used to configure the query builder of the edge.
func (gmq *GroupMemberQuery) WithGroup(opts ...func(*GroupQuery)) *GroupMemberQuery {
	query := &GroupQuery{config: gmq.config}
	for _, opt := range opts {
		opt(query)
	}
	gmq.withGroup = query
	return gmq
}

// WithInviter tells the query-builder to eager-load the nodes that are connected to
// the "inviter" edge. The optional arguments are used to configure the query builder of the edge.
func (gmq *GroupMemberQuery) WithInviter(opts ...func(*MemberQuery)) *GroupMemberQuery {
	query := &MemberQuery{config: gmq.config}
	for _, opt := range opts {
		opt(query)
	}
	gmq.withInviter = query
	return gmq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.GroupMember.Query().
//		GroupBy(groupmember.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (gmq *GroupMemberQuery) GroupBy(field string, fields ...string) *GroupMemberGroupBy {
	grbuild := &GroupMemberGroupBy{config: gmq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := gmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return gmq.sqlQuery(ctx), nil
	}
	grbuild.label = groupmember.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.GroupMember.Query().
//		Select(groupmember.FieldCreatedAt).
//		Scan(ctx, &v)
func (gmq *GroupMemberQuery) Select(fields ...string) *GroupMemberSelect {
	gmq.fields = append(gmq.fields, fields...)
	selbuild := &GroupMemberSelect{GroupMemberQuery: gmq}
	selbuild.label = groupmember.Label
	selbuild.flds, selbuild.scan = &gmq.fields, selbuild.Scan
	return selbuild
}

func (gmq *GroupMemberQuery) prepareQuery(ctx context.Context) error {
	for _, f := range gmq.fields {
		if !groupmember.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if gmq.path != nil {
		prev, err := gmq.path(ctx)
		if err != nil {
			return err
		}
		gmq.sql = prev
	}
	return nil
}

func (gmq *GroupMemberQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*GroupMember, error) {
	var (
		nodes       = []*GroupMember{}
		_spec       = gmq.querySpec()
		loadedTypes = [3]bool{
			gmq.withMember != nil,
			gmq.withGroup != nil,
			gmq.withInviter != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*GroupMember).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &GroupMember{config: gmq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(gmq.modifiers) > 0 {
		_spec.Modifiers = gmq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, gmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := gmq.withMember; query != nil {
		if err := gmq.loadMember(ctx, query, nodes, nil,
			func(n *GroupMember, e *Member) { n.Edges.Member = e }); err != nil {
			return nil, err
		}
	}
	if query := gmq.withGroup; query != nil {
		if err := gmq.loadGroup(ctx, query, nodes, nil,
			func(n *GroupMember, e *Group) { n.Edges.Group = e }); err != nil {
			return nil, err
		}
	}
	if query := gmq.withInviter; query != nil {
		if err := gmq.loadInviter(ctx, query, nodes, nil,
			func(n *GroupMember, e *Member) { n.Edges.Inviter = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (gmq *GroupMemberQuery) loadMember(ctx context.Context, query *MemberQuery, nodes []*GroupMember, init func(*GroupMember), assign func(*GroupMember, *Member)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*GroupMember)
	for i := range nodes {
		fk := nodes[i].MemberID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(member.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "member_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (gmq *GroupMemberQuery) loadGroup(ctx context.Context, query *GroupQuery, nodes []*GroupMember, init func(*GroupMember), assign func(*GroupMember, *Group)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*GroupMember)
	for i := range nodes {
		fk := nodes[i].GroupID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(group.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "group_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (gmq *GroupMemberQuery) loadInviter(ctx context.Context, query *MemberQuery, nodes []*GroupMember, init func(*GroupMember), assign func(*GroupMember, *Member)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*GroupMember)
	for i := range nodes {
		if nodes[i].InviterID == nil {
			continue
		}
		fk := *nodes[i].InviterID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(member.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "inviter_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (gmq *GroupMemberQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := gmq.querySpec()
	if len(gmq.modifiers) > 0 {
		_spec.Modifiers = gmq.modifiers
	}
	_spec.Node.Columns = gmq.fields
	if len(gmq.fields) > 0 {
		_spec.Unique = gmq.unique != nil && *gmq.unique
	}
	return sqlgraph.CountNodes(ctx, gmq.driver, _spec)
}

func (gmq *GroupMemberQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := gmq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (gmq *GroupMemberQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   groupmember.Table,
			Columns: groupmember.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: groupmember.FieldID,
			},
		},
		From:   gmq.sql,
		Unique: true,
	}
	if unique := gmq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := gmq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, groupmember.FieldID)
		for i := range fields {
			if fields[i] != groupmember.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := gmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := gmq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := gmq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := gmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (gmq *GroupMemberQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(gmq.driver.Dialect())
	t1 := builder.Table(groupmember.Table)
	columns := gmq.fields
	if len(columns) == 0 {
		columns = groupmember.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if gmq.sql != nil {
		selector = gmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if gmq.unique != nil && *gmq.unique {
		selector.Distinct()
	}
	for _, m := range gmq.modifiers {
		m(selector)
	}
	for _, p := range gmq.predicates {
		p(selector)
	}
	for _, p := range gmq.order {
		p(selector)
	}
	if offset := gmq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := gmq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (gmq *GroupMemberQuery) Modify(modifiers ...func(s *sql.Selector)) *GroupMemberSelect {
	gmq.modifiers = append(gmq.modifiers, modifiers...)
	return gmq.Select()
}

// GroupMemberGroupBy is the group-by builder for GroupMember entities.
type GroupMemberGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (gmgb *GroupMemberGroupBy) Aggregate(fns ...AggregateFunc) *GroupMemberGroupBy {
	gmgb.fns = append(gmgb.fns, fns...)
	return gmgb
}

// Scan applies the group-by query and scans the result into the given value.
func (gmgb *GroupMemberGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := gmgb.path(ctx)
	if err != nil {
		return err
	}
	gmgb.sql = query
	return gmgb.sqlScan(ctx, v)
}

func (gmgb *GroupMemberGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range gmgb.fields {
		if !groupmember.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := gmgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := gmgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (gmgb *GroupMemberGroupBy) sqlQuery() *sql.Selector {
	selector := gmgb.sql.Select()
	aggregation := make([]string, 0, len(gmgb.fns))
	for _, fn := range gmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(gmgb.fields)+len(gmgb.fns))
		for _, f := range gmgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(gmgb.fields...)...)
}

// GroupMemberSelect is the builder for selecting fields of GroupMember entities.
type GroupMemberSelect struct {
	*GroupMemberQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (gms *GroupMemberSelect) Scan(ctx context.Context, v interface{}) error {
	if err := gms.prepareQuery(ctx); err != nil {
		return err
	}
	gms.sql = gms.GroupMemberQuery.sqlQuery(ctx)
	return gms.sqlScan(ctx, v)
}

func (gms *GroupMemberSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := gms.sql.Query()
	if err := gms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (gms *GroupMemberSelect) Modify(modifiers ...func(s *sql.Selector)) *GroupMemberSelect {
	gms.modifiers = append(gms.modifiers, modifiers...)
	return gms
}
