// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/chatpuppy/puppychat/internal/ent/key"
	"github.com/chatpuppy/puppychat/internal/ent/predicate"
)

// KeyUpdate is the builder for updating Key entities.
type KeyUpdate struct {
	config
	hooks     []Hook
	mutation  *KeyMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the KeyUpdate builder.
func (ku *KeyUpdate) Where(ps ...predicate.Key) *KeyUpdate {
	ku.mutation.Where(ps...)
	return ku
}

// SetGroupID sets the "group_id" field.
func (ku *KeyUpdate) SetGroupID(u uint64) *KeyUpdate {
	ku.mutation.ResetGroupID()
	ku.mutation.SetGroupID(u)
	return ku
}

// AddGroupID adds u to the "group_id" field.
func (ku *KeyUpdate) AddGroupID(u int64) *KeyUpdate {
	ku.mutation.AddGroupID(u)
	return ku
}

// SetMemberID sets the "member_id" field.
func (ku *KeyUpdate) SetMemberID(u uint64) *KeyUpdate {
	ku.mutation.ResetMemberID()
	ku.mutation.SetMemberID(u)
	return ku
}

// AddMemberID adds u to the "member_id" field.
func (ku *KeyUpdate) AddMemberID(u int64) *KeyUpdate {
	ku.mutation.AddMemberID(u)
	return ku
}

// SetKey sets the "key" field.
func (ku *KeyUpdate) SetKey(s string) *KeyUpdate {
	ku.mutation.SetKey(s)
	return ku
}

// SetEnable sets the "enable" field.
func (ku *KeyUpdate) SetEnable(b bool) *KeyUpdate {
	ku.mutation.SetEnable(b)
	return ku
}

// SetNillableEnable sets the "enable" field if the given value is not nil.
func (ku *KeyUpdate) SetNillableEnable(b *bool) *KeyUpdate {
	if b != nil {
		ku.SetEnable(*b)
	}
	return ku
}

// Mutation returns the KeyMutation object of the builder.
func (ku *KeyUpdate) Mutation() *KeyMutation {
	return ku.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ku *KeyUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ku.hooks) == 0 {
		affected, err = ku.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*KeyMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ku.mutation = mutation
			affected, err = ku.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ku.hooks) - 1; i >= 0; i-- {
			if ku.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ku.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ku.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (ku *KeyUpdate) SaveX(ctx context.Context) int {
	affected, err := ku.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ku *KeyUpdate) Exec(ctx context.Context) error {
	_, err := ku.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ku *KeyUpdate) ExecX(ctx context.Context) {
	if err := ku.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (ku *KeyUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *KeyUpdate {
	ku.modifiers = append(ku.modifiers, modifiers...)
	return ku
}

func (ku *KeyUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   key.Table,
			Columns: key.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: key.FieldID,
			},
		},
	}
	if ps := ku.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ku.mutation.GroupID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint64,
			Value:  value,
			Column: key.FieldGroupID,
		})
	}
	if value, ok := ku.mutation.AddedGroupID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint64,
			Value:  value,
			Column: key.FieldGroupID,
		})
	}
	if value, ok := ku.mutation.MemberID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint64,
			Value:  value,
			Column: key.FieldMemberID,
		})
	}
	if value, ok := ku.mutation.AddedMemberID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint64,
			Value:  value,
			Column: key.FieldMemberID,
		})
	}
	if value, ok := ku.mutation.Key(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: key.FieldKey,
		})
	}
	if value, ok := ku.mutation.Enable(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: key.FieldEnable,
		})
	}
	_spec.Modifiers = ku.modifiers
	if n, err = sqlgraph.UpdateNodes(ctx, ku.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{key.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// KeyUpdateOne is the builder for updating a single Key entity.
type KeyUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *KeyMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetGroupID sets the "group_id" field.
func (kuo *KeyUpdateOne) SetGroupID(u uint64) *KeyUpdateOne {
	kuo.mutation.ResetGroupID()
	kuo.mutation.SetGroupID(u)
	return kuo
}

// AddGroupID adds u to the "group_id" field.
func (kuo *KeyUpdateOne) AddGroupID(u int64) *KeyUpdateOne {
	kuo.mutation.AddGroupID(u)
	return kuo
}

// SetMemberID sets the "member_id" field.
func (kuo *KeyUpdateOne) SetMemberID(u uint64) *KeyUpdateOne {
	kuo.mutation.ResetMemberID()
	kuo.mutation.SetMemberID(u)
	return kuo
}

// AddMemberID adds u to the "member_id" field.
func (kuo *KeyUpdateOne) AddMemberID(u int64) *KeyUpdateOne {
	kuo.mutation.AddMemberID(u)
	return kuo
}

// SetKey sets the "key" field.
func (kuo *KeyUpdateOne) SetKey(s string) *KeyUpdateOne {
	kuo.mutation.SetKey(s)
	return kuo
}

// SetEnable sets the "enable" field.
func (kuo *KeyUpdateOne) SetEnable(b bool) *KeyUpdateOne {
	kuo.mutation.SetEnable(b)
	return kuo
}

// SetNillableEnable sets the "enable" field if the given value is not nil.
func (kuo *KeyUpdateOne) SetNillableEnable(b *bool) *KeyUpdateOne {
	if b != nil {
		kuo.SetEnable(*b)
	}
	return kuo
}

// Mutation returns the KeyMutation object of the builder.
func (kuo *KeyUpdateOne) Mutation() *KeyMutation {
	return kuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (kuo *KeyUpdateOne) Select(field string, fields ...string) *KeyUpdateOne {
	kuo.fields = append([]string{field}, fields...)
	return kuo
}

// Save executes the query and returns the updated Key entity.
func (kuo *KeyUpdateOne) Save(ctx context.Context) (*Key, error) {
	var (
		err  error
		node *Key
	)
	if len(kuo.hooks) == 0 {
		node, err = kuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*KeyMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			kuo.mutation = mutation
			node, err = kuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(kuo.hooks) - 1; i >= 0; i-- {
			if kuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = kuo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, kuo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Key)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from KeyMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (kuo *KeyUpdateOne) SaveX(ctx context.Context) *Key {
	node, err := kuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (kuo *KeyUpdateOne) Exec(ctx context.Context) error {
	_, err := kuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (kuo *KeyUpdateOne) ExecX(ctx context.Context) {
	if err := kuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (kuo *KeyUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *KeyUpdateOne {
	kuo.modifiers = append(kuo.modifiers, modifiers...)
	return kuo
}

func (kuo *KeyUpdateOne) sqlSave(ctx context.Context) (_node *Key, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   key.Table,
			Columns: key.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: key.FieldID,
			},
		},
	}
	id, ok := kuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Key.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := kuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, key.FieldID)
		for _, f := range fields {
			if !key.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != key.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := kuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := kuo.mutation.GroupID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint64,
			Value:  value,
			Column: key.FieldGroupID,
		})
	}
	if value, ok := kuo.mutation.AddedGroupID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint64,
			Value:  value,
			Column: key.FieldGroupID,
		})
	}
	if value, ok := kuo.mutation.MemberID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint64,
			Value:  value,
			Column: key.FieldMemberID,
		})
	}
	if value, ok := kuo.mutation.AddedMemberID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint64,
			Value:  value,
			Column: key.FieldMemberID,
		})
	}
	if value, ok := kuo.mutation.Key(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: key.FieldKey,
		})
	}
	if value, ok := kuo.mutation.Enable(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: key.FieldEnable,
		})
	}
	_spec.Modifiers = kuo.modifiers
	_node = &Key{config: kuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, kuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{key.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
